### ISSUE TITLE
[DISCUSSION][NEW FEATURE]Costumizable gridlines of the playfield

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#39]
Hey guys, what do you think about having the option for costumizing the gridlines of the background.(regarding horizontal lines so one can subdevide his own playfield into visual parts)
DEF said, therefore the field background image should be generated.

**Comment by Noir-** [comment]
I'm wondering since when Cultris 2 had a background grid? I'd rather vote for removing this completely :stuck_out_tongue: 
I'm also thinking that the GUI is very alpha and will be changed in a way that it outclass Cultris 2. (At least I hope so)

**Comment by zDEFz** [comment]
I think customization wouldn't hurt.
The playfield background can generated with simple rectangles anyways.

**Comment by Noir-** [comment]
Customization always increases complexity, not only in the code but also in the user interface. I also never heard a single complaint since 2011 that anyone wants grid lines in the background of Cultris 2.  Ok I'm mean :laughing:

Sure we could do this but I guess it's rather a low priority task. But it's nice to get warm with the source code. Maybe we could add a "easy" label to it?

**Comment by jefgenowitsch** [comment]
I think I have to clarify my idea. Look at the Screenshot: http://imgur.com/a/csHlf
I really like the vertical "lines" in the background image.
My idea was that the user could tick an option which would show or hide the horizontal thin lines. So that the user can "subdivide" his playfield for his own needs. I don't know if this is much to code or implement. Please teach me a better.

PS: I wasn't **complaining**
PPS: A lot of things weren't asked in Cultris for known reasons. That's why I don't count this as an argument. The game is still at the beginning of getting somehow unique.
PPPS: I wanted to wait with such feature requests but I was told that it is better to do it this way. Please give me an update on this.

**Comment by zDEFz** [comment]
#4 

>  Noted. It's all good.
> Keep the feedback flowing!

**Comment by rmcat** [comment]
Personally, I do not like gridlines. I am for minimizing the number of options. Cultris is very user-friendly because of that.

Other reasons for not having gridlines are:
- Game would look cleaner.
- Game would have a more standard look across streams and recordings.
- Invisible play difficulty would be decreased.

**Comment by kroyee** [comment]
I also like the idea of minimizing options. There is nothing worse then opening a new game and having 200 different options to choose from, and not knowing what half of them are/means.

If a player really wanted gridlines, they could change their fieldbackground.png.
If the resource files are directly available in the game folder players could also easily make their own "themes" by modifying the images and sounds. This would at the same time not effect the clean and simple options-menu.

We could have a themes section on the forum and let players post their custom made themes there.

**Comment by Noir-** [comment]
:+1:  for less options but good hackability

**Comment by jefgenowitsch** [comment]
Wow, I didn't know that this way will be possible in the future. I welcome this solution!
