### ISSUE TITLE
[UX] One assignment per key

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#40]
**Steps to reproduce:**

Assign a key

**Expected result:**

The assigned key is locked and cannot be assigned multiple times

**Actual Result**

The assigned key isn't locked

**Comment by zDEFz** [comment]
I don't understand why i cant just do

```
if (options->left != (options->right))
	{
		LeB->connect("pressed", &UI::setKey, this, LeB, std::ref(options->left));
		SFKeyToString(options->left, keyname);
		LeB->setText(keyname);
		GenOpt->add(LeB);
	}
else {}
```

This is just a simple check if the set key for left is the set key for right.

**BTW if that happens it should NULL the next identical key that is assigned already.**

How can i compare a reassigned Key?

I thought i can test and if it works i do a specific algorithm for checking that.

Have to say things are really confusing because there is not enough documentation for it.

**Comment by kroyee** [comment]
The documentation is quite underwhelming for sure.

You should probably look at the examples/tutorials on the [TGUI](https://tgui.eu) site to better understand how the GUI objects work.

To put it simple, the block of code is just creating a button, binding a function that will be called when the button is pressed and then adding this button to the main GUI object.

You then need to look at that function (UI::setKey) to see what happens when the button is pressed.

This function will in turn prepare the client to accept a key-input and store it, by displaying the "Press any key" message on the screen and wait for input through the UI::putKey function. (it's not really waiting since we can't let the code block, it's just passing all event on to putKey until one event is a KeyPress)

When a key is pressed the UI::putKey will receive that event, and bind the corresponding key to the right variable (one the keys in options)

At this point (inside the UI::putKey function) we would want to iterate through all the other keys in options and if it finds a duplicate, then unset that key.

I'm not sure if that explanation helped at all. The TGUI site explains the UI object very well, and when that is clear it should be easier to understand what is doing what.

**Comment by zDEFz** [comment]
BTW i found out how to compare but i need to get a valid comparision.
**SFKeyToString(event.key.code, name); does it for another purpose right?**
But it's actually void so it isn't returning anything but printing

At the moment i compare

```
if 
(
				*key != options->left
				&&
				*key != options->right
				&&
				*key != options->down
				&&
				*key != options->rccw
				&&
				*key  != options->rccw
				&&
				*key != options->r180
				&&
				*key != options->hd
				&&
				*key != options->chat
				&&
				*key != options->chat
				&&
				*key != options->score
				&&
				*key != options->away
)
```

Which is wrong since its comparing *key "0x00af9b70" to  characters like "A" (0) 
How can i convert *key so i have valid comparisions?

**Comment by kroyee** [comment]
No, the comparison is right. *key and options->left is the same kind of object, otherwise it would not compile.

But *key is a pointer to one of the keys. So if your trying to set the options->left then *key will be pointing to options->left, and you are doing the equivalent of:
if (options->left != options->left)
witch will always be false.

A better aproach would be to do this:
```
if (event.key.code == options->right)
  options->right = sf::Keyboard::Unknown;
if (event.key.code == options->left)
  options->left = sf::Keyboard::Unknown;
if (event.key.code == options->down)
  options->down = sf::Keyboard::Unknown;
// -- and so on for all the keys, and after you can do
*key = event.key.code;
```

BUT... IF something was changed to Unknown, you also need to update the text on that button.
So here some rework would be needed to make sure we have a way to access the button objects.

This could be done by giving them a name when we added them to the gui before with:
GenOpt->add(LeB);
if we change this to:
GenOpt->add(LeB, "BindLeft");

then we can retrieve that object by calling
`gui.get<tgui::Button>("BindLeft")->setText("");`

we are getting a generic tgui::Widget object-pointer from our call to gui.get, we are then casting it to a tgui::Button (witch is a derived class of tgui::widget) and calling it's setText function with the value of and empry string (making the button display nothing instead of whatever was there before).

I would again encourage you to go to the TGUI website and look at the tutorials there. Things are very well explained.

**Comment by zDEFz** [comment]
The if does work now - however it throws now this message:
_edit_
Exception at 0x0FB8F7FB (sfml-system-d-2.dll) in SpeedBlocks.exe: 0xC0000005: Access violation at read on Position 0x00000238

**Comment by kroyee** [comment]
What does it mean in english?

**Comment by zDEFz** [comment]
Whatever i will give you my source file.

**Comment by zDEFz** [comment]
http://pastebin.com/cpgHYTNQ

**Comment by texus** [comment]
The error means you are accessing a null pointer. In this case gui.get is returning a nullptr because the widget can't be found and you are attempting to call setText on this nullptr.

The reason why the "BindLeft" widget can't be found is because it was never added to the gui directly. Either search it in the panel that contains it (i.e. `GenOpt->get<tgui::Button>("BindLeft")`) or let the gui do a recursive search (i.e. `gui.get<tgui::Button>("BindLeft", true)`).

**Comment by zDEFz** [comment]
I tried `gui.get<tgui::Button>("BindLeft", true)`
At least it doesn't crash anymore

Think that i did something wrong before. Because the field doens't get set to unknown or anything similiar (double assigning still possible)

Normally it should clear the field if it's already persistent right?

**Comment by kroyee** [comment]
You did a few strange things, but the code should work if you put
`gui.get<tgui::Button>("BindLeft", true);`

This will however only clear the button "BindLeft" no matter witch one was found as a duplicate.

```
if (event.key.code == options->left)
                options->left = sf::Keyboard::Unknown;
```
should be
```
if (event.key.code == options->left) {
                options->left = sf::Keyboard::Unknown;
                gui.get<tgui::Button>("BindLeft", true)->setText("");
}
```
the same would go for all the other, but you would have to give them equivalent names like you did with
`GenOpt->add(LeB, "BindLeft");`

if you look below this line the next block is
```
tgui::Label::Ptr RiL = themeTG->load("Label");
    RiL->setPosition(0, 103);
    RiL->setSize(90, 30);
    RiL->setText("Right");
    RiL->setHorizontalAlignment(tgui::Label::HorizontalAlignment::Right);
    GenOpt->add(RiL);
    tgui::Button::Ptr RiB = themeTG->load("Button");
    RiB->setPosition(100, 100);
    RiB->connect("pressed", &UI::setKey, this, RiB, std::ref(options->right));
    SFKeyToString(options->right, keyname);
    RiB->setText(keyname);
    GenOpt->add(RiB);
```
witch is the label and button for the right key (you can see the text on the label "Right")
so here again you need to change to
`GenOpt->add(RiB, "BindRight");`
and then add that down in the putKey function like
```
if (event.key.code == options->right) {
                options->right = sf::Keyboard::Unknown;
                gui.get<tgui::Button>("BindRight", true)->setText("");
}
```
and so on.

Then at the bottom of putKey you can replace
```
if (
                *key != options->left
                &&
                *key != options->right
                &&
                *key != options->down
                &&
                *key != options->rccw
                &&
                *key  != options->rccw
                &&
                *key != options->r180
                &&
                *key != options->hd
                &&
                *key != options->chat
                &&
                *key != options->chat
                &&
                *key != options->score
                &&
                *key != options->away
                )
            {
                button->setText(name);
            }
           
 
            else {
                try {
                    button->setText(name);
                    std::cout << "not " << name;
                    gui.get<tgui::Button>("BindLeft")->setText("");
                    }
                catch(...){}
               
                }
```

with simply
`button->setText(name);`

**Comment by zDEFz** [comment]
I did fix it but github doesn't do it correctly with the formatting :/
Why did you disable uploads @kroyee 
Since that i can't upload files anymore and tabs are file changes 
pls let me upload the file properly.

**Comment by kroyee** [comment]
What uploads?

**Comment by kroyee** [comment]
If you want to upload something to the repo you should open a pull request.

**Comment by zDEFz** [comment]
I can not. I tried to update my repo and uploaded the file and if i compare mine to you it says it is up to date.
Because of that i did click Upload files before and did upload the single file.
But now it says that it is disabled :/

I can not simply open a pull request without having changes from mine to your repo. 
Idk its kinda hard to do also...

**Comment by kroyee** [comment]
I don't know. That's probably something wrong on your side.
Nothing has been disabled in the repo.

**Comment by kroyee** [comment]
Maybe [this](http://stackoverflow.com/questions/34664316/why-is-the-create-pull-request-menu-item-in-visual-studio-2015-always-disabled) helps.

**Comment by zDEFz** [comment]
Im always doing this over the web ui... I try to delete my repository and reupload

**Comment by zDEFz** [comment]
Problem was Visual Studio interfering with it.
Better you have a seperate folder where you DONT compile and just as a sync folder.
So you need to copy over your changes in the folder and then push/pull in a branch that is not master.
Strange
