### ISSUE TITLE
[UX] bug: viewing real time piece positions while spectating

### ISSUE THREAD

**Issue by kb1900** [kroyee/SpeedBlocks#77]
currently the game has very poor viewing enjoyment as we can not see in real time how players manipulate there pieces. instead we get a frame-by-frame type of viewing experience where we see their field after each line clear or a few line clears. in cultris 2, we can view softdropping etc. in "real time"

@kroyee has informed me this is a bug and not a missing feature

**Comment by kroyee** [comment]
So just to clarify here...
You can see pieces that opponents have placed, but it only updates once in a while.
The piece that is "in the air" you cannot see at all. Not even when the field updates.

Is this correct?

**Comment by kb1900** [comment]
@kroyee correct

no ghost piece, no piece "in the air" even after the field updates

**Comment by kroyee** [comment]
Ok, I will make the best guess I can and include something that might help in the next commit.
If it does not work I'm going to have to wait to figure this out until I have a Mac next to me so I can try some different things that way.

The playfield and the piece in the air is sent in the same packet, so that excludes anything being wrong with the network traffic. The only thing I can think of is some sort of casting issue from sf::Uint8 to short, so I'm including some static_cast<short> in the compressor class to see if that makes any difference.

If someone has a Mac with Xcode and is willing to run some testings that would be great.
