### ISSUE TITLE
[UX] Need of an Apply / Save button per Tab OR changed - remember to discard/save

### ISSUE THREAD

**Issue by zDEFz** [kroyee/SpeedBlocks#9]
Turns out - options can be saved in the configuration file.
But this is done by pressing apply on Video Tab.
Would be much more convenient if there was a apply / save button on each tab 

OR

If user has made any changes - prompting to **discard** the changes or to **save** them

**Comment by kroyee** [comment]
Options are changed as soon as they are changed. Only the video options differ because it would be highly inconvenient if settings there updated as soon as you touched something.
Config file is only generated when you quit the game, up until that point all changes are just stored in variables in the game.

**Comment by zDEFz** [comment]
Oh that makes sense. I did exit the game through the console everytime.

In that case i can discard the issue
