### ISSUE TITLE
Make fails on [100%] Linking CXX executable SpeedBlocks

### ISSUE THREAD

**Issue by kalebodonnell** [kroyee/SpeedBlocks#94]
I have compiled SFML from source by the CLI instructions [here](https://www.sfml-dev.org/tutorials/2.5/compile-with-cmake.php)

What I did to compile SFML:
cmake .
make 
sudo make install

What I did to compile SpeedBlocks:
cmake .
make

CMake output:
[CMakeLog.txt](https://github.com/kroyee/SpeedBlocks/files/2046946/CMakeLog.txt)
Make output:
[makeLog.txt](https://github.com/kroyee/SpeedBlocks/files/2046942/makeLog.txt)

**Comment by kroyee** [comment]
From the output in CMakeLog it looks like you have SFML libraries in both /usr/lib/x86_64-linux-gnu and /usr/local/lib that are conflicting.
I would try removing one of them and recompile SpeedBlocks.

I also see that you are using SFML 2.5.0. I have not had time to update from 2.4.2 yet so I have not been able to test if it works without any modification yet, but since it's a minor update it should run without any problems.

Either way your linking issue is not due to the SFML version.

**Comment by kroyee** [comment]
If you never changed CMAKE_INSTALL_PREFIX while installing SFML it would put all the libsmfl-*.so files in /usr/local/lib by default.

My guess is that you have installed the sfml-dev from your packet manager previously or you had an older version of SFML already installed on your system.

**Comment by kalebodonnell** [comment]
Yep it was that I had SMFL In both /usr/local/lib and /usr/lib/x86_64-linux-gnu, dont realy know how they ended up in both as libsmfl-dev is not listed as installed in my package manager, but I temporaly moved the ones from /usr/lib/x86_64-linux-gnu and it worked. Thanks for that
